README.md
This is more accurate to my understanding of Rust licensing, and is
representative of the approach we have taken.
I removed most analysis of the license and left it an explanation of
how to pick a license that is compatible with Rust.
This flips the recommendation about MIT vs. Apache. MIT is the less
restrictive license and is more compatible with Rust than Apache. We
don't accept Apache only software in rust-lang projects, but we do
accept MIT-only.
It also removes discussion of license headers. They were a mistake in Rust
and just confuse the issue.
r? @dtolnay 
I'd like to land this before publicizing the guidelines.
cc @aturon
=> Rework the license guideline

LICENSE-APACHE, LICENSE-MIT, README.md
I didn't find a license on the [`old`](https://github.com/brson/rust-api-guidelines/tree/old) branch. Hopefully this is okay.
@brson
=> License of the guidelines

README.md
Missing comma between `Hash` and `Debug` in C-COMMON-TRAITS overview section.
=> Add single missing comma in README

README.md
Apparently the macro was renamed pre-rustc-1.0: <https://github.com/rust-lang/rust/issues/17489>
=> [C-VALIDATE] Replace fail! with panic!

src/interoperability.md
=> Fix typo in interoperability.md

deploy.sh
Looks like the `TRAVIS_BRANCH` variable uses the target branch for PR builds rather than the source. So all PRs will actually replace the `gh-pages` branch.
I've pilfered an alternative way to get the branch name in travis from [here](https://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/) that reports the source branch properly.
Just going to make sure this PR itself doesn't trigger the docs to upload, and that an upload is triggered when it's merged.
=> Only upload on builds against master branch

src/documentation.md
I wrote a little helper crate for keeping version numbers in sync with the crate version: https://crates.io/crates/version-sync. I hope it will be useful to people reading the guidelines and humbly suggest including it.
=> Suggest using version-sync to keep html_root_url in sync

.travis.yml
I wrote a little helper crate for keeping version numbers in sync with the crate version: https://crates.io/crates/version-sync. I hope it will be useful to people reading the guidelines and humbly suggest including it.
=> travis: cache build artifacts

.travis.yml
This uses cargo-update to install newer versions of mdbook. The
caching introduced in #128 ensures that we only update when needed.
Fixes #129.
=> travis: install latest version of mdbook

src/naming.md
Because it looks like a camel with a single hump in the middle: 🐪
=> PascalCase has leading capitalization, camelCase does not 🐪

src/necessities.md
Catch up with rust-lang/cargo#4898, which deprecated '/' in favor of vanilla SPDX license expressions.
=> necessities: Use "MIT OR Apache-2.0"

book.toml
[Avoid][1]:
```console
$ mdbook build
2018-04-17 22:35:25 [WARN] (mdbook::config): It looks like you are using the legacy book.toml format.
2018-04-17 22:35:25 [WARN] (mdbook::config): We'll parse it for now, but you should probably convert to the new format.
2018-04-17 22:35:25 [WARN] (mdbook::config): See the mdbook documentation for more details, although as a rule of thumb
2018-04-17 22:35:25 [WARN] (mdbook::config): just move all top level configuration entries like `title`, `author` and
2018-04-17 22:35:25 [WARN] (mdbook::config): `description` under a table called `[book]`, move the `destination` entry
2018-04-17 22:35:25 [WARN] (mdbook::config): from `[output.html]`, renamed to `build-dir`, under a table called
2018-04-17 22:35:25 [WARN] (mdbook::config): `[build]`, and it should …
```
=> book.toml: Add a [book] table (and a description)

src/documentation.md
Since main can now return a result, the documentation examples that use `?` can be simplified. This is also the method used by the [rustdoc documentation](https://doc.rust-lang.org/rustdoc/documentation-tests.html).
=> Remove try_main and return Result

src/interoperability.md
In the “C-COMMON-TRAITS” section of “Interoperability”, the following text appears:
> There is no way for `webapp` to add `Display` to `url`, …
This seems to say “implement `Display` for `url` (the crate)” instead of “implement `Display` for `url::Url` (the type)”.
This pull request fixes this, by capitalizing “`url`” into “`Url`”.
=> src/interoperability: change “url” to “Url”

CONTRIBUTING.md, README.md, src/about.md, src/future-proofing.md, src/naming.md, src/type-safety.md
* https://github.com/rust-lang-nursery/api-guidelines is now https://github.com/rust-lang/api-guidelines
* https://rust-lang-nursery.github.io/api-guidelines is now https://rust-lang.github.io/api-guidelines
* https://rust-lang-nursery.github.io/edition-guide is now https://rust-lang.github.io/edition-guide
* https://github.com/rust-lang-nursery/bitflags is now https://github.com/bitflags/bitflags
=> Update URLs for things which previously were in rust-lang-nursery

src/interoperability.md
* The error chapter still mentions `cause()` but not `source()` - Fixed
* The error chapter says users should use `Display` instead of `description()` but it still encourages implementing it. That method is now fully deprecated (nightly) and should not be implemented at all for new errors.
=> Fix error chapter with regards to deprecated description() and cause()

src/documentation.md
Sadly the warning is not visible until the doctest fails.
=> Rust 2018 warns when boxed Error misses dyn

CONTRIBUTING.md
This ensures the highlights are left to the content examples themselves, rather than to the descriptions, and makes it easier to compare both versions.
The diff of this PR is a little hard to read, so I suggest viewing the [rendered file](https://github.com/waldyrious/api-guidelines/blob/patch-1/CONTRIBUTING.md#guidelines-for-the-guidelines) to see the result.
=> CONTRIBUTING.md: use context lines in diff blocks

src/necessities.md
The instructions recommended adding a link to license files that it didn't mention otherwise.
This commit adds a paragraphs making it explicit that (and how) those files should be created.
=> necessities.md: complete licensing instructions

CONTRIBUTING.md, src/necessities.md
It seems the Rust FAQ was dropped with website redesign (https://github.com/rust-lang/www.rust-lang.org/issues/291). This question doesn't seem to be answered on any current resource, but the old website is still available.
Also updated link to Code of Conduct.
=> Fix broken link to Rust FAQ

src/documentation.md
The new text explains how to add regular markdown links and how to add
link targets. In particular it makes it clear that rustdoc link
targets go at the end of the docstring rather than inline.
=> Add more explanatory text to the C-LINK section

src/naming.md
The description "Conversions prefixed `to_`, on the other hand, typically stay at the same level of abstraction but do some work to change one representation into another." risks overlapping the ideas of `to_` and `into_` to memory. Instead using "from... to" helps reduce that overlap by using to with `to_`.
=> Avoid using "into" when explaining `to_*`

CONTRIBUTING.md, README.md
I've converted a lot of our open discussions on new guidelines into GitHub Discussions so we can keep our issue tracker focused on concrete guidelines and recommendations.
This is a new GitHub feature so users might not be used to going to Discussions yet to find things.
r? @dtolnay
=> Add readme link to Discussions

src/checklist.md, src/documentation.md
See https://github.com/rust-lang/api-guidelines/issues/229 for discussion.
r? @BurntSushi
=> Don't recommend setting html_root_url

src/future-proofing.md
The std::error::Error trait broadly follows the same role as Debug and Display, and is equally inappropriate to have in bounds on a generic type parameter of a data structure.
```rust
// do not do this
pub struct S<E: Error> {...}
impl<E: Error> S<E> {...}
```
```rust
// do this
pub struct S<E> {...}
impl<E: Error> S<E> {...}
```
The typical scenario this makes a meaningful difference is in code like:
```rust
pub enum ThingError<E: Error> {
Problem1(String),
Problem2,
Problem3(E),
}
// somebody else's code downstream
fn needs_retry<E>(e: &ThingError<E>) -> bool {
match e {
Problem1(_) => true,
Problem2 | Problem3(_) => false,
}
}
```
:sadface:
```console
error[E0277]: the trait bound `E: std::error::Error` is not satisfied
--> src/lib.rs:10:22
|
2  | pub enum ThingError<E: Error> {
| …
```
=> Add Error trait to list of clear-cut nevers in c-struct-bounds

src/checklist.md, src/documentation.md
Since 1.46.0 (https://github.com/rust-lang/cargo/pull/8277), cargo can automatically detect the value of the readme field.
https://doc.rust-lang.org/stable/cargo/reference/manifest.html#the-readme-field
> If no value is specified for this field, and a file named README.md, README.txt or README exists in the package root, then the name of that file will be used. You can suppress this behavior by setting this field to false. If the field is set to true, a default value of README.md will be assumed.
=> Remove readme field from C-METADATA

.github/workflows/deploy.yml
The v2 implementation uses Node 12, which is end-of-life on April 30, 2022. See https://nodejs.org/en/about/releases/. Update to v3, which is based on Node 16 whose support lasts until April 30, 2024.
=> Update GitHub Actions actions/checkout@v2 to v3

src/dependability.md
In accordance with [RFC 221](https://github.com/rust-lang/rfcs/pull/221).
=> Replace "task failure" with "panicking" in C-DTOR-FAIL

src/type-safety.md
Accepting options after a non-option argument is a glibc extension[1]. Move the option before the non-option to be POSIX compliant.
[1]: https://www.gnu.org/software/libc/manual/html_node/Using-Getopt.html#index-getopt
=> C-BUILDER: Avoid GNUism in example

src/naming.md
Nightly rustc has recently expanded the `unused_imports` lint to warn in scenarios like this (rust-lang/rust#121708):
```rust
#![cfg_attr(not(feature = "std"), no_std)]
#[cfg(feature = "alloc")]
extern crate alloc;
#[cfg(feature = "alloc")]
pub mod alloc_only {
use alloc::boxed::Box;
pub fn foo(_bar: Box<u8>) {}
}
```
(only gives a warning if `feature = "std"` is enabled)
<details><summary>warning</summary>
```
warning: the item `Box` is imported redundantly
--> src/lib.rs:8:9
|
8   |     use alloc::boxed::Box;
|         ^^^^^^^^^^^^^^^^^
|
::: /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/prelude/mod.rs:125:13
|
125 |     pub use super::v1::*;
|             --------- the item `Box` is already defined here
|
= note: …
```
=> C-FEATURE: improve the example for conditional `no_std`

src/naming.md
There is a broken link in examples. I've replaced it with a new active link.
=> C-GETTER: Replace a broken link with a new active one
